export const listViewData = {
  asset_number: 500,
  assets: [
    {
      create_date: '2021-08-10T07:24:30.087+0000',
      type: '2021-08-10-Overstreet comic book collection',
      title: 'SUPER Comic Book 50th Anniversary 10 GEM MINT ',
      imageLink: '/images/list/list-item.svg',
      price: {
        icon: 'etherum',
        cryptoValue: '3.1',
        dolarValue: '6234.33',
      },
      Category: 'Baseball',
      Grade: 'Baseball',
      Brand: 'Casio',
      Price: 'Gamning',
      Collection: 'Spring',
      Status: 'Sold',
    },
    {
      create_date: '2021-09-30T07:24:30.087+0000',
      type: '2021-09-30-Overstreet comic book collection',
      title: 'Very new Comic Book 50th Anniversary 10 GEM MINT ',
      imageLink: '/images/list/list-item.svg',
      price: {
        icon: 'etherum',
        cryptoValue: '4.1',
        dolarValue: '6234.33',
      },
      Category: 'Baseball',
      Grade: 'Baseball',
      Brand: 'Casio',
      Price: 'Gamning',
      Collection: 'Autumn',
      Status: 'Sold',
    },
    {
      create_date: '2021-10-13T07:24:30.087+0000',
      type: '2021-10-13-Overstreet comic book collection',
      title: ' NEW Book 50th Anniversary 10 GEM MINT ',
      imageLink: '/images/list/list-item.svg',
      price: {
        icon: 'etherum',
        cryptoValue: '5.1',
        dolarValue: '6234.33',
      },
      Category: 'Marvel',
      Grade: 'Marvel',
      Brand: 'Sony',
      Price: 'Others',
      Collection: 'Autumn',
      Status: 'Available',
    },
    {
      create_date: '2021-10-10T07:24:30.087+0000',
      type: '2021-10-10-Overstreet comic book collection',
      title: 'Overstreet Comic Book 50th Anniversary 10 GEM MINT ',
      imageLink: '/images/list/list-item.svg',
      price: {
        icon: 'etherum',
        cryptoValue: '2.1',
        dolarValue: '6234.33',
      },
      Category: 'Marvel',
      Grade: 'Marvel',
      Brand: 'Sony',
      Price: 'Others',
      Collection: 'Autumn',
      Status: 'Available',
    },
    {
      create_date: '2021-10-10T07:24:30.087+0000',
      type: '2021-10-10-Overstreet comic book collection',
      title: 'Overstreet Comic Book 50th Anniversary 10 GEM MINT ',
      imageLink: '/images/list/list-item.svg',
      price: {
        icon: 'etherum',
        cryptoValue: '2.1',
        dolarValue: '6234.33',
      },
      Category: 'Marvel',
      Grade: 'Marvel',
      Brand: 'Sony',
      Price: 'Others',
      Collection: 'Autumn',
      Status: 'Available',
    },
    {
      create_date: '2021-10-10T07:24:30.087+0000',
      type: '2021-10-10-Overstreet comic book collection',
      title: 'Overstreet Comic Book 50th Anniversary 10 GEM MINT ',
      imageLink: '/images/list/list-item.svg',
      price: {
        icon: 'etherum',
        cryptoValue: '2.1',
        dolarValue: '6234.33',
      },
      Category: 'Marvel',
      Grade: 'Marvel',
      Brand: 'Sony',
      Price: 'Others',
      Collection: 'Autumn',
      Status: 'Available',
    },
  ],
};

export const mockCards = [
  {
    create_date: '2021-08-10T07:24:30.087+0000',
    type: '2021-08-10-Overstreet comic book collection',
    title: 'SUPER Comic Book 50th Anniversary 10 GEM MINT ',
    imageLink: '/images/list/list-item.svg',
    price: {
      icon: 'etherum',
      cryptoValue: '3.1',
      dolarValue: '6234.33',
    },
    Category: 'Baseball',
    Grade: 'Baseball',
    Brand: 'Casio',
    Price: 'Gamning',
    Collection: 'Spring',
    Status: 'Sold',
  },
  {
    create_date: '2021-08-10T07:24:30.087+0000',
    type: '2021-08-10-Overstreet comic book collection',
    title: 'SUPER Comic Book 50th Anniversary 10 GEM MINT ',
    imageLink: '/images/list/list-item.svg',
    price: {
      icon: 'etherum',
      cryptoValue: '3.1',
      dolarValue: '6234.33',
    },
    Category: 'Baseball',
    Grade: 'Baseball',
    Brand: 'Casio',
    Price: 'Gamning',
    Collection: 'Spring',
    Status: 'Sold',
  },
  {
    create_date: '2021-08-10T07:24:30.087+0000',
    type: '2021-08-10-Overstreet comic book collection',
    title: 'SUPER Comic Book 50th Anniversary 10 GEM MINT ',
    imageLink: '/images/list/list-item.svg',
    price: {
      icon: 'etherum',
      cryptoValue: '3.1',
      dolarValue: '6234.33',
    },
    Category: 'Baseball',
    Grade: 'Baseball',
    Brand: 'Casio',
    Price: 'Gamning',
    Collection: 'Spring',
    Status: 'Sold',
  },
  {
    create_date: '2021-08-10T07:24:30.087+0000',
    type: '2021-08-10-Overstreet comic book collection',
    title: 'SUPER Comic Book 50th Anniversary 10 GEM MINT ',
    imageLink: '/images/list/list-item.svg',
    price: {
      icon: 'etherum',
      cryptoValue: '3.1',
      dolarValue: '6234.33',
    },
    Category: 'Baseball',
    Grade: 'Baseball',
    Brand: 'Casio',
    Price: 'Gamning',
    Collection: 'Spring',
    Status: 'Sold',
  },
  {
    create_date: '2021-08-10T07:24:30.087+0000',
    type: '2021-08-10-Overstreet comic book collection',
    title: 'SUPER Comic Book 50th Anniversary 10 GEM MINT ',
    imageLink: '/images/list/list-item.svg',
    price: {
      icon: 'etherum',
      cryptoValue: '3.1',
      dolarValue: '6234.33',
    },
    Category: 'Baseball',
    Grade: 'Baseball',
    Brand: 'Casio',
    Price: 'Gamning',
    Collection: 'Spring',
    Status: 'Sold',
  },
  {
    create_date: '2021-08-10T07:24:30.087+0000',
    type: '2021-08-10-Overstreet comic book collection',
    title: 'SUPER Comic Book 50th Anniversary 10 GEM MINT ',
    imageLink: '/images/list/list-item.svg',
    price: {
      icon: 'etherum',
      cryptoValue: '3.1',
      dolarValue: '6234.33',
    },
    Category: 'Baseball',
    Grade: 'Baseball',
    Brand: 'Casio',
    Price: 'Gamning',
    Collection: 'Spring',
    Status: 'Sold',
  },
];

export const mockCategoryFilters = [
  { categoryName: 'Category', filters: ['Marvel', 'Baseball', 'Racing'] },
  {
    categoryName: 'Grade',
    filters: ['Marvel', 'Baseball', 'Racing', 'Football', 'Soccer', 'Hockey', 'Combat Sports'],
  },
  { categoryName: 'Brand', filters: ['Sony', 'Casio'] },
  { categoryName: 'Price', filters: ['Gaming', 'Others'] },
  { categoryName: 'Collection', filters: ['Autumn', 'Spring'] },
  { categoryName: 'Status', filters: ['Available', 'Sold', 'Auction'] },
];
