import { Button, styled } from '@mui/material';

export const CardWrapper = styled('div')(({ theme }) => ({
  //   backgroundColor: theme.palette.grey[50],
  width: '100%',
  margin: '0 auto',
  padding: '12px 24px',
  display: 'flex',
  flexDirection: 'column',
  border: '1px solid green',
  flex: '1',
  justifyContent: 'center',
  '& label': {
    color: theme.palette.grey[600],
    fontWeight: '300',
    letterSpacing: '0.025em',
  },
  '& button': {
    whiteSpace: 'nowrap',
    border: '0',
    outline: '0',
    display: 'inline-block',
    height: '40px',
    lineHeight: '40px',
    padding: '0 14px',
    boxShadow: '0 4px 6px rgba(50, 50, 93, 0.11), 0 1px 3px rgba(0, 0, 0, 0.08)',
    color: '#fff',
    borderRadius: '4px',
    fontSize: '15px',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: '0.025em',
    backgroundColor: '#6772e5',
    textDecoration: 'none',
    '-webkit-transition': 'all 150ms ease',
    transition: 'all 150ms ease',
    marginTop: '10px',
  },
  '& button:hover': {
    color: '#fff',
    cursor: 'pointer',
    backgroundColor: '#7795f8',
    transform: 'translateY(-1px)',
    boxShadow: '0 7px 14px rgba(50, 50, 93, 0.1), 0 3px 6px rgba(0, 0, 0, 0.08)',
  },

  '.StripeElement': {
    display: 'block',
    margin: '10px 0 20px 0',
    maxWidth: '500px',
    padding: '10px 14px',
    fontSize: '1em',
    boxShadow: 'rgba(50, 50, 93, 0.14902) 0px 1px 3px, rgba(0, 0, 0, 0.0196078) 0px 1px 0px',
    outline: `1px solid  ${theme.palette.grey[500]}`,
    borderRadius: '4px',
    background: 'white',
    transition: 'all 250ms ease-in-out',
    '&:hover': {
      outline: `2px solid ${theme.palette.grey[500]}`,
    },
  },
}));

export const ConfirmPaymentButton = styled(Button)(({ theme }) => ({
  '&.MuiButtonBase-root': {
    color: 'white',
    backgroundColor: theme.palette.primary.main,
    height: '52px',
    padding: '12px 32px',
    width: '100%',
    //   margin: '8px 24px',
    fontSize: '16px',
    lineHeight: '24px',
    borderRadius: '8px',
    border: `1px solid ${theme.palette.primary.main}`,
    '&:hover': {
      color: theme.palette.primary.main,
      backgroundColor: theme.palette.secondary.main,
    },
    '&:disabled': {
      backgroundColor: theme.palette.grey[200],
      color: theme.palette.grey[400],
      borderColor: theme.palette.grey[400],
      cursor: 'not-allowed',
      pointerEvents: 'all',
    },
    [theme.breakpoints.down('sm')]: {
      margin: '0 12px',
      fontWeight: '500',
      fontSize: '14px',
      lineHeight: '20px',
    },
  },
}));
