name: 'Staging'
on:
  push:
    branches:
      - "develop"
  workflow_dispatch:
    inputs:
        force:
          description: 'Force deploy'
          required: true
          default: 'true'
jobs:
  on-success:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
      - name: 'Detect Changed Files'
        uses: dorny/paths-filter@v2
        id: changed-files
        with:
          filters: |
            src:
              - .github/**
              - .gitignore
              - MAKEFILE
              - README.md
      - name: Configure AWS credentials
        if: steps.changed-files.outputs.src == 'false' || github.event.inputs.force == 'true'
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: gh-actions-deploy-role
          role-duration-seconds: 1200
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: ecr-login
        if: |
          (steps.changed-files.outputs.src == 'false' ||
          github.event.inputs.force == 'true') &&
          steps.aws-creds.outcome == 'success'
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to Amazon ECR
        id: ecr
        if: |
          (steps.changed-files.outputs.src == 'false' ||
          github.event.inputs.force == 'true') &&
          steps.ecr-login.outcome == 'success'
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          ECR_REPOSITORY: web-staging
          IMAGE_TAG: latest
          DOCKER_FILE: Dockerfile.ecs
          NEXT_PUBLIC_BACKEND_URL: https://api.staging.pwcc.jump.co/v1
          NEXT_PUBLIC_FRONTEND_URL: https://staging.pwcc.jump.co/v1
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          NEXT_PUBLIC_SENTRY_ENV: staging
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_STRIPE_SECRET_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_SECRET_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          docker build --platform=linux/amd64 \
            --build-arg NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL \
            --build-arg NEXT_PUBLIC_FRONTEND_URL=$NEXT_PUBLIC_FRONTEND_URL \
            --build-arg NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN \
            --build-arg NEXT_PUBLIC_SENTRY_ENV=$NEXT_PUBLIC_SENTRY_ENV \
            --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY \
            --build-arg NEXT_PUBLIC_STRIPE_SECRET_KEY=$NEXT_PUBLIC_STRIPE_SECRET_KEY \
            --build-arg SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN \
            --build-arg SENTRY_RELEASE=$GITHUB_SHA \
            -f $DOCKER_FILE \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Restart WEB ECS services to enfore pulling latest/newest ECR image
        if: |
          (steps.changed-files.outputs.src == 'false' ||
          github.event.inputs.force == 'true') &&
          steps.ecr.outcome == 'success'
        env:
          CLUSTER_NAME: jumpco-cluster-staging
          SERVICE_NAME: web-staging
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
      - name: Slack Notification
        if: steps.changed-files.outputs.src == 'false' || github.event.inputs.force == 'true'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: jump-dev
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: |
            Deploy ${{ job.status }}

            Details: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

            Code Deployed: https://github.com/${{github.repository}}/tree/develop
          SLACK_TITLE: "Web Deployment: Staging Environment"
          SLACK_WEBHOOK: ${{ secrets.SLACK_DEPLOYMENTS_WEBHOOK_URL }}
          SLACK_FOOTER: "Powered by our GitHub automated deploys"
