name: 'Test'
on:
  pull_request:
    branches:
      - "**"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  main:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Setup NodeJS 14'
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: 'Install Dependencies'
        run: yarn install
      - name: 'Lint'
        run: yarn lint
      - name: 'Build'
        env:
          NEXT_PUBLIC_BACKEND_URL: https://api.staging.pwcc.jump.co/v1
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          NEXT_PUBLIC_SENTRY_ENV: staging
        run: yarn build
      - name: 'Run Tests'
        run: yarn test:cov
